version: '3'
services:
  publisher:
    build: .
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "5000:5000"
    command: bash -c "nodemon app.js"

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"