version: '3'
services:
  publisher:
    build: .
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "5000:5000"
    environment:
      DB_HOST: "mongodb://poll:poll@mongo:27017/poll?authSource=poll"
    command: bash -c "nodemon app.js"

  mongo: 
    image: "mongo"
    ports:
      - "27017:27017"
    volumes:
      - "mongodb:/data/db"

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"

volumes:
  mongodb:
    driver: local