version: '3'
services:
  publisher:
    build: .
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "5000:5000"
    environment:
      DB_HOST: "mongodb://poll:poll@mongo:27017/poll?authSource=poll"
    restart: on-failure  
    depends_on:
      - elasticsearch  
    command: bash -c "nodemon app.js"

  mongo: 
    image: "mongo"
    ports:
      - "27017:27017"
    volumes:
      - "mongodb:/data/db"

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
  
  elasticsearch:
    image: "docker.elastic.co/elasticsearch/elasticsearch:7.13.2"
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      discovery.type: "single-node"
  
  kibana:
    image: "docker.elastic.co/kibana/kibana:7.13.2"
    ports:
      - "5601:5601"
    environment:
      ELASTICSEARCH_HOSTS: "http://elasticsearch:9200"

volumes:
  mongodb:
    driver: local
