version: '3'
services:
  publisher:
    build: .
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "5000:5000"
    environment:
      DB_HOST: "mongodb://mongo:27017/admin"
    command: bash -c "nodemon app.js"

  mongo: 
    image: "mongo"
    ports:
      - "27017:27017"
    volumes:
      - "mongodb:/data/db"

volumes:
  mongodb:
    driver: local