module.exports = {
  vedioContents: [{
    title: 'Iron Man',
    summary: 'This is Iron Man',
    contentType: 'Movie',
    genre: 'Hero',
    category: 'Hero',
    casts: ['Iron Man'],
  },
  {
    title: 'Iron Man',
    summary: 'This is Iron Man',
    contentType: 'Movie',
    genre: 'Hero',
    category: 'Hero',
    casts: ['Iron Man'],
  },
  {
    title: 'Iron Man 2',
    summary: 'This is Iron Man 2',
    contentType: 'Movie',
    genre: 'Hero',
    category: 'Hero',
    casts: ['Iron Man'],
  },
  {
    title: 'Superman Man',
    summary: 'This is Superman Man',
    contentType: 'Movie',
    genre: 'Hero',
    category: 'Hero',
    casts: ['Superman Man'],
  },
  {
    title: 'Superman Man',
    summary: 'This is Superman Man',
    contentType: 'Movie',
    genre: 'Hero',
    category: 'Hero',
    casts: ['Superman Man'],
  },
  {
    title: 'Superman Man 2',
    summary: 'This is Superman Man 2',
    contentType: 'Movie',
    genre: 'Hero',
    category: 'Hero',
    casts: ['Superman Man'],
  },
  {
    title: 'Love Movie',
    summary: 'This is Love Movie',
    contentType: 'Movie',
    genre: 'Romantic',
    category: 'Romantic',
    casts: ['Mary'],
  },
  {
    title: 'Love Movie 2',
    summary: 'This is Love Movie 2',
    contentType: 'Movie',
    genre: 'Romantic',
    category: 'Romantic',
    casts: ['Mary'],
  },
  {
    title: 'Running Man',
    summary: 'This is Running Man',
    contentType: 'Series',
    genre: 'Funny',
    category: 'Funny',
    casts: ['Peter'],
  }],
};
